### ISSUE TITLE
Can't install latest version of the gem using Ruby 2.7

### ISSUE THREAD

**Issue by alexeisersun** [railslove/epics#157]
Hello there!

We try to upgrade `epics` gem in a project with Ruby 2.7. Judging by `epics.gemspec` file, Ruby 2.7 is still supported:

```ruby
  spec.required_ruby_version = '>= 2.7'
```

However, same `epics.gemspec` file specifies Nokogiri version which requires Ruby 3+: 😅 

```ruby
  spec.add_dependency 'nokogiri', '>= 1.16.5'
```

From my perspective, one of the following workarounds can be done:

1. relax Nokogiri version, so that the gem is installable on Ruby 2.7
2. bump required Ruby version to 3+ in gemspec

Could you please advise what can be done in this case?

**Comment by tobischo** [comment]
Since nokogiri keeps addressing relevant security issues regularly, it does not make sense to relax that requirement.

Ruby language version 2.7 is not officially supported anymore by its maintainers.
My suggestion is for you to update your projects to using a newer ruby version.

While the language requirement of >= 2.7 might be sligtly misleading with other gems requiring a newer Ruby, it does not currently warrant a new release in my opinion.

**Comment by alexeisersun** [comment]
Thanks for prompt response!
